dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
cache: pip
install:
  - pip install docutils sphinx
  - pip install -e .[test,louvain,leiden]
env:
  - MPLBACKEND=Agg
script:
  - pytest --ignore=scanpy/tests/_images
  - python setup.py check --restructuredtext --strict
  - rst2html.py --halt=2 README.rst >/dev/null
