name: pypsa
channels:
  - conda-forge
dependencies:
  - python
  - six
  - numpy
  - pyomo
  - scipy
  - pandas>=0.24.0
  - matplotlib
  - networkx>=1.10
  - pyomo
  - cartopy>=0.16
  - coincbc
  - glpk
