language: python
python:
- '2.7'
- '3.5'
install:
- pip install numpy scipy
- python setup.py install
script:
- python pypower/t/test_pypower.py
deploy:
  provider: pypi
  user: rwl
  password:
    secure: MIOPCmmh3W+ZfFo7WZyT1S9PmvUa7MQnx/LNGsjHgVqIBfArnJKStPViKhONXOAIhR2fTyNtz7BUfCvuwFgniqhxK/MpQ+flutNaxPLdIn60xSzzTmOlra/1bSoSpQGAvYEA1Wdof8iV+ILqvCY9fR8JXFmPGr/oyjd+PKFgEc8=
  on:
    tags: true
    repo: rwl/PYPOWER
    branch: master
    python: '2.7'
